import { useEffect, useMemo, useState } from 'react';

interface Rule { id: number; position: number; descriptionContains: string; categoryId: string }
interface Category { id: string; name: string; deleted: boolean }
interface Group { id: string; name: string; categories: Category[] }

export function CategorizationRulesPage() {
  const [rules, setRules] = useState<Rule[]>(); const [groups, setGroups] = useState<Group[]>([]);
  const [match, setMatch] = useState(''); const [category, setCategory] = useState(''); const [editing, setEditing] = useState<number>(); const [error, setError] = useState('');
  const categories = useMemo(() => groups.flatMap((group) => group.categories), [groups]);
  const load = () => Promise.all([fetch('/api/categorization-rules').then((r) => r.json() as Promise<{ rules: Rule[] }>), fetch('/api/categories').then((r) => r.json() as Promise<{ groups: Group[] }>)]).then(([a, b]) => { setRules(a.rules); setGroups(b.groups); }).catch(() => setError('Rules or categories could not be loaded.'));
  useEffect(() => { void load(); }, []);
  const save = async () => { const response = await fetch(editing ? `/api/categorization-rules/${editing}` : '/api/categorization-rules', { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ descriptionContains: match, categoryId: category }) }); if (!response.ok) { setError((await response.json() as { message?: string }).message ?? 'Rule could not be saved.'); return; } setMatch(''); setCategory(''); setEditing(undefined); setError(''); await load(); };
  const remove = async (id: number) => { if (!confirm('Delete this categorization rule?')) return; await fetch(`/api/categorization-rules/${id}`, { method: 'DELETE' }); await load(); };
  const move = async (index: number, delta: number) => { if (!rules) return; const next = [...rules]; const target = index + delta; if (target < 0 || target >= next.length) return; const current = next[index]!; next[index] = next[target]!; next[target] = current; setRules(next); await fetch('/api/categorization-rules/order', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ruleIds: next.map((rule) => rule.id) }) }); };
  return <main><a className="back-link" href="/">← Back to statements</a><header className="dashboard-header"><div><p className="eyebrow">Categories & rules</p><h1>Manage categorization rules</h1><p>Rules apply to new statements in the order shown.</p></div></header><section><h2>{editing ? 'Edit rule' : 'Create a rule'}</h2><form onSubmit={(event) => { event.preventDefault(); void save(); }}><label>Description contains <input value={match} onChange={(event) => setMatch(event.target.value)} required /></label><label>Assign category <select value={category} onChange={(event) => setCategory(event.target.value)} required><option value="">Select a category</option>{groups.map((group) => <optgroup key={group.id} label={group.name}>{group.categories.filter((item) => !item.deleted).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>)}</select></label><button type="submit">{editing ? 'Save changes' : 'Add rule'}</button>{editing && <button type="button" onClick={() => { setEditing(undefined); setMatch(''); setCategory(''); }}>Cancel</button>}</form>{error && <p role="alert">{error}</p>}</section><section><h2>Saved rules</h2>{!rules?.length ? <p>No categorization rules saved yet.</p> : <ol className="rules-list">{rules.map((rule, index) => <li key={rule.id}><span><strong>{rule.descriptionContains}</strong> → {categories.find((item) => item.id === rule.categoryId)?.name ?? `${rule.categoryId} (deleted)`}</span><span className="rule-actions"><button type="button" onClick={() => { setEditing(rule.id); setMatch(rule.descriptionContains); setCategory(rule.categoryId); }}>Edit</button><button type="button" onClick={() => void remove(rule.id)}>Delete</button><button type="button" onClick={() => void move(index, -1)} disabled={index === 0}>↑</button><button type="button" onClick={() => void move(index, 1)} disabled={index === rules.length - 1}>↓</button></span></li>)}</ol>}</section></main>;
}
