import { useEffect, useMemo, useState } from 'react';

interface Rule { id: number; position: number; descriptionContains: string; categoryId: string | null; excluded: boolean | null; parserId: string | null }
interface Category { id: string; name: string; deleted: boolean }
interface Group { id: string; name: string; categories: Category[] }
interface Parser { id: string; name: string }

export function CategorizationRulesPage() {
  const [rules, setRules] = useState<Rule[]>(); const [groups, setGroups] = useState<Group[]>([]); const [parsers, setParsers] = useState<Parser[]>([]);
  const [match, setMatch] = useState(''); const [category, setCategory] = useState(''); const [inclusion, setInclusion] = useState(''); const [parserId, setParserId] = useState(''); const [editing, setEditing] = useState<number>(); const [error, setError] = useState('');
  const categories = useMemo(() => groups.flatMap((group) => group.categories), [groups]);
  const load = () => Promise.all([fetch('/api/categorization-rules').then((response) => response.json() as Promise<{ rules: Rule[] }>), fetch('/api/categories').then((response) => response.json() as Promise<{ groups: Group[] }>), fetch('/api/parsers').then((response) => response.ok ? response.json() as Promise<{ parsers: Parser[] }> : { parsers: [] })]).then(([loadedRules, loadedGroups, loadedParsers]) => { setRules(loadedRules.rules); setGroups(loadedGroups.groups); setParsers(loadedParsers.parsers); }).catch(() => setError('Rules or categories could not be loaded.'));
  useEffect(() => { void load(); }, []);
  const reset = () => { setMatch(''); setCategory(''); setInclusion(''); setParserId(''); setEditing(undefined); };
  const save = async () => { const excluded = inclusion === 'exclude' ? true : inclusion === 'include' ? false : null; const response = await fetch(editing ? `/api/categorization-rules/${editing}` : '/api/categorization-rules', { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ descriptionContains: match, categoryId: category || null, excluded, parserId: parserId || null }) }); if (!response.ok) { setError((await response.json() as { message?: string }).message ?? 'Rule could not be saved.'); return; } reset(); setError(''); await load(); };
  const remove = async (id: number) => { if (!confirm('Delete this transaction rule?')) return; await fetch(`/api/categorization-rules/${id}`, { method: 'DELETE' }); await load(); };
  const move = async (index: number, delta: number) => { if (!rules) return; const next = [...rules]; const target = index + delta; if (target < 0 || target >= next.length) return; const current = next[index]!; next[index] = next[target]!; next[target] = current; setRules(next); await fetch('/api/categorization-rules/order', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ruleIds: next.map((rule) => rule.id) }) }); };
  return <main><section><h2>{editing ? 'Edit rule' : 'Create a rule'}</h2><form onSubmit={(event) => { event.preventDefault(); void save(); }}><label>Description contains <input value={match} onChange={(event) => setMatch(event.target.value)} required /></label><label>Category <select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Leave category unchanged</option>{groups.map((group) => <optgroup key={group.id} label={group.name}>{group.categories.filter((item) => !item.deleted).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</optgroup>)}</select></label><label>Publishing <select value={inclusion} onChange={(event) => setInclusion(event.target.value)}><option value="">Leave inclusion unchanged</option><option value="include">Include transaction</option><option value="exclude">Exclude transaction</option></select></label><label>Apply rule to <select value={parserId} onChange={(event) => setParserId(event.target.value)}><option value="">All statements</option>{parsers.map((parser) => <option key={parser.id} value={parser.id}>Only {parser.name} statements</option>)}</select></label><button type="submit" disabled={!match.trim() || (!category && !inclusion)}>{editing ? 'Save changes' : 'Add rule'}</button>{editing && <button type="button" onClick={reset}>Cancel</button>}</form>{error && <p role="alert">{error}</p>}</section><section><h2>Saved rules</h2>{!rules?.length ? <p>No transaction rules saved yet.</p> : <ol className="rules-list">{rules.map((rule, index) => { const effects = [rule.categoryId ? `Category: ${categories.find((item) => item.id === rule.categoryId)?.name ?? `${rule.categoryId} (deleted)`}` : null, rule.excluded === true ? 'Exclude from publishing' : rule.excluded === false ? 'Include in publishing' : null].filter(Boolean).join(' · '); return <li key={rule.id}><span><strong>{rule.descriptionContains}</strong> → {effects} <small>{rule.parserId ? `Only ${parsers.find((parser) => parser.id === rule.parserId)?.name ?? rule.parserId}` : 'All statements'}</small></span><span className="rule-actions"><button type="button" onClick={() => { setEditing(rule.id); setMatch(rule.descriptionContains); setCategory(rule.categoryId ?? ''); setInclusion(rule.excluded === true ? 'exclude' : rule.excluded === false ? 'include' : ''); setParserId(rule.parserId ?? ''); }}>Edit</button><button type="button" onClick={() => void remove(rule.id)}>Delete</button><button type="button" onClick={() => void move(index, -1)} disabled={index === 0}>↑</button><button type="button" onClick={() => void move(index, 1)} disabled={index === rules.length - 1}>↓</button></span></li>; })}</ol>}</section></main>;
}
