import { useEffect, useState } from 'react';

import { CategoryPathLabel, GroupedCategorySelect } from './grouped-category-select.js';
import { GroupedParserSelect, type ParserSelectOption } from './grouped-parser-select.js';

interface Rule { id: number; position: number; descriptionContains: string; categoryId: string | null; excluded: boolean | null; parserId: string | null }
interface Category { id: string; name: string; deleted: boolean }
interface Group { id: string; name: string; categories: Category[] }
type Parser = ParserSelectOption;

export function CategorizationRulesPage({ onRulesChanged }: { onRulesChanged?: () => void } = {}) {
  const [rules, setRules] = useState<Rule[]>(); const [groups, setGroups] = useState<Group[]>([]); const [parsers, setParsers] = useState<Parser[]>([]);
  const [match, setMatch] = useState(''); const [category, setCategory] = useState(''); const [inclusion, setInclusion] = useState(''); const [parserId, setParserId] = useState(''); const [editing, setEditing] = useState<number>(); const [error, setError] = useState('');
  const load = () => Promise.all([fetch('/api/categorization-rules').then((response) => response.json() as Promise<{ rules: Rule[] }>), fetch('/api/categories').then((response) => response.json() as Promise<{ groups: Group[] }>), fetch('/api/parser-settings').then((response) => response.ok ? response.json() as Promise<{ parsers: Parser[] }> : { parsers: [] })]).then(([loadedRules, loadedGroups, loadedParsers]) => { setRules(loadedRules.rules); setGroups(loadedGroups.groups); setParsers(loadedParsers.parsers); }).catch(() => setError('Rules or categories could not be loaded.'));
  useEffect(() => { void load(); }, []);
  const reset = () => { setMatch(''); setCategory(''); setInclusion(''); setParserId(''); setEditing(undefined); };
  const save = async () => { const excluded = inclusion === 'exclude' ? true : inclusion === 'include' ? false : null; const response = await fetch(editing ? `/api/categorization-rules/${editing}` : '/api/categorization-rules', { method: editing ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ descriptionContains: match, categoryId: category || null, excluded, parserId: parserId || null }) }); if (!response.ok) { setError((await response.json() as { message?: string }).message ?? 'Rule could not be saved.'); return; } reset(); setError(''); await load(); onRulesChanged?.(); };
  const remove = async (id: number) => { if (!confirm('Delete this transaction rule?')) return; await fetch(`/api/categorization-rules/${id}`, { method: 'DELETE' }); await load(); onRulesChanged?.(); };
  const move = async (index: number, delta: number) => { if (!rules) return; const next = [...rules]; const target = index + delta; if (target < 0 || target >= next.length) return; const current = next[index]!; next[index] = next[target]!; next[target] = current; setRules(next); await fetch('/api/categorization-rules/order', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ruleIds: next.map((rule) => rule.id) }) }); onRulesChanged?.(); };
  return <main><section><h2>{editing ? 'Edit rule' : 'Create a rule'}</h2><form onSubmit={(event) => { event.preventDefault(); void save(); }}><label>Description contains <input value={match} onChange={(event) => setMatch(event.target.value)} required /></label><label>Category <GroupedCategorySelect emptyLabel="Leave category unchanged" groups={groups} value={category} onChange={setCategory} /></label><label>Publishing <select value={inclusion} onChange={(event) => setInclusion(event.target.value)}><option value="">Leave inclusion unchanged</option><option value="include">Include transaction</option><option value="exclude">Exclude transaction</option></select></label><label>Apply rule to <GroupedParserSelect ariaLabel="Apply rule to parser" emptyLabel="All statements" optionLabel={(parser) => `Only ${parser.name} statements${parser.enabled === false ? ' (hidden)' : ''}`} parsers={parsers} value={parserId} onChange={setParserId} /></label><button type="submit" disabled={!match.trim() || (!category && !inclusion)}>{editing ? 'Save changes' : 'Add rule'}</button>{editing && <button type="button" onClick={reset}>Cancel</button>}</form>{error && <p role="alert">{error}</p>}</section><section><h2>Saved rules</h2>{!rules?.length ? <p>No transaction rules saved yet.</p> : <ol className="rules-list">{rules.map((rule, index) => { const inclusionEffect = rule.excluded === true ? 'Exclude from publishing' : rule.excluded === false ? 'Include in publishing' : null; return <li key={rule.id}><span><strong>{rule.descriptionContains}</strong> → {rule.categoryId && <>Category: <CategoryPathLabel categoryId={rule.categoryId} groups={groups} />{inclusionEffect && ' · '}</>}{inclusionEffect} <small>{rule.parserId ? `Only ${parsers.find((parser) => parser.id === rule.parserId)?.name ?? rule.parserId}` : 'All statements'}</small></span><span className="rule-actions"><button type="button" onClick={() => { setEditing(rule.id); setMatch(rule.descriptionContains); setCategory(rule.categoryId ?? ''); setInclusion(rule.excluded === true ? 'exclude' : rule.excluded === false ? 'include' : ''); setParserId(rule.parserId ?? ''); }}>Edit</button><button type="button" onClick={() => void remove(rule.id)}>Delete</button><button type="button" onClick={() => void move(index, -1)} disabled={index === 0}>↑</button><button type="button" onClick={() => void move(index, 1)} disabled={index === rules.length - 1}>↓</button></span></li>; })}</ol>}</section></main>;
}
